{
    'name': "Proxima SMS",
    'version': "1.0.3-49e3c8037070c3b55c8d23d24b70e968b5ffc9b0",
    'author': "Proxima Technologies Cameroon",
    'category': "Tools",
    'price': 112,
    'currency': 'USD',
    'support': "proxima.cm@gmail.com",
    'summary':'A SMS module for Odoo instances',
    'description':'Allows you to send SMS from multiple gateways',
    'license':'LGPL-3',
    'website': 'https://proxima-cm.github.io',
    'data': [
        'data/ir.cron.xml',
        'data/ir.model.access.csv',
        'data/sms.gateway.csv',
        'data/mail.message.subtype.csv',
        'data/menu.xml',
        'views/sms_views.xml',
        'views/res_partner_views.xml',
        'views/sms_message_views.xml',
        'views/sms_template_views.xml',
        'views/sms_account_views.xml',
        'views/sms_number_views.xml',
        'views/sms_compose_views.xml',
        'views/ir_actions_server_views.xml',
        'views/ir_actions_todo.xml',
        'security/ir.model.access.csv',
    ],
    'depends': ['mail','base_automation'],
    'images':[
        'images/undraw_emails_6uqr.png',
    ],
    'qweb': ['static/src/xml/sms_compose.xml'],
    'installable': True,
    'application': True
}
