{
    'name': "Multi SMS Gateway: Twilio Integration, ...",
    'version': "1.0.4",
    'author': "Abdou Nasser",
    'category': "Extra Tools",
    'price': 50,
    'currency': 'EUR',
    "support": "abdounasser202@gmail.com",
    "website": "https://formation-odoo.blogspot.com",
    'summary':'A SMS module for Odoo instances',
    'description':'Allows you to send SMS from multiple gateways, including Twilio',
    'license':'LGPL-3',
    'data': [
        'data/ir.cron.xml',
        'data/ir.model.access.csv',
        'data/sms.gateway.csv',
        'data/mail.message.subtype.csv',
        'data/menu.xml',
        'views/sms_views.xml',
        'views/res_partner_views.xml',
        'views/sms_message_views.xml',
        'views/sms_template_views.xml',
        'views/sms_account_views.xml',
        'views/sms_number_views.xml',
        'views/sms_compose_views.xml',
        'views/ir_actions_server_views.xml',
        'views/ir_actions_todo.xml',
        'security/ir.model.access.csv',
    ],
    'depends': ['mail','base_automation'],
    'images':[
        'images/undraw_emails_6uqr.png',
    ],
    'qweb': ['static/src/xml/sms_compose.xml'],
    'installable': True,
    'application': True
}
