{
    "name": "GoodCRM - v10 For customization",
    "summary": "Make your CRM great",
    "category": "CRM",
    'price': 40,
    'currency': 'USD',
    "images": ['images/undraw_segmentation_uioo.png'],
    "version": "0.0.1",
    "author": "Proxima Technologies Cameroon",
    "support": "proxima.cm@gmail.com",
    "website": "https://proxima-cm.github.io",
    "license": "LGPL-3",
    "depends": [
        "base",
        "crm",
        "sale_crm",
        "web_notify"
    ],
    "data": [
        'data/menu.xml',
        'views/objectif_commercial_view.xml',
        'views/res_partner.xml',
        'views/pipeline.xml',
        'views/activities.xml',
        'views/dashboard.xml',
        'views/quotations.xml',
        'wizards/evaluer_objectif.xml',
    ],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
